DROP TABLE IF EXISTS INSTRUMENT;

CREATE TABLE instrument
  (
     ticker          VARCHAR(50) PRIMARY KEY,
     instrument_type VARCHAR(30) NOT NULL,
     underlying_ticker VARCHAR(50),
     expected_return DOUBLE,
     annualized_sd   DOUBLE,
     option_type     VARCHAR(10),
     strike_price    DOUBLE,
     strike_date     DATE
 );

INSERT INTO instrument
            (ticker,
             instrument_type,
             underlying_ticker,
             expected_return,
             annualized_sd,
             option_type,
             strike_price,
             strike_date)
VALUES      ( 'AAPL',
              'STOCK',
              NULL,
              0.5,
              0.8,
              NULL,
              NULL,
              NULL),
            ('TSLA',
             'STOCK',
             NULL,
             0.9,
             0.6,
             NULL,
             NULL,
             NULL),
            ('AAPL-OCT-2025-300-C',
             'EUROPEAN_OPTION',
             'AAPL',
             NULL,
             NULL,
             'CALL',
             300,
             '2025-10-17'),
             ('AAPL-OCT-2025-110-P',
             'EUROPEAN_OPTION',
             'AAPL',
             NULL,
             NULL,
             'PUT',
             110,
             '2025-10-17'),
            ('TSLA-NOV-2025-400-C',
             'EUROPEAN_OPTION',
             'TSLA',
             NULL,
             NULL,
             'CALL',
             400,
             '2025-11-01'),
             ('TSLA-DEC-2025-400-P',
             'EUROPEAN_OPTION',
             'TSLA',
              NULL,
              NULL,
             'PUT',
             400,
             '2025-12-01')